[package]
name = "xd"
version = "0.1.0"
authors = ["Ainevsia <zhipengxu@sjtu.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.8"
exitfailure = "0.5.1"
colored = "1.9.2"
